CONFIG_DIR ?= ../../ubiworks/library/ubinos/app
CONFIG_NAME ?= hello_world_netduinoplus2_qemu

LIBRARY_DIR ?= ../../ubiworks/library

# DEBUG_SERVER_SERIAL ?= "683755679"
# DEBUG_SERVER_PORT ?= "2341"

include makefile.mk

